services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - media_data:/app/media
    environment:
      - DB_URL=postgresql+asyncpg://sigma:qwerty10@45.80.129.209:5432/sigma
      - LLM_API_URL=http://45.80.129.209:9011
      - LLM_WINDOW_SEC=1.5
      - LLM_TARGET_FPS=10
      - LLM_FRAMES_PER_WINDOW=5
      - LLM_MAX_HIGHLIGHTS=10

volumes:
  media_data:
