services:
  # db:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_USER: sigma
  #     POSTGRES_PASSWORD: sigma
  #     POSTGRES_DB: sigma
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U sigma"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./media:/app/media
    environment:
      - DB_URL=postgresql+asyncpg://sigma:qwerty10@127.0.0.1:5432/sigma
      - LLM_API_URL=http://45.80.129.209:9011
      - LLM_WINDOW_SEC=1.5
      - LLM_TARGET_FPS=10
      - LLM_FRAMES_PER_WINDOW=5
      - LLM_MAX_HIGHLIGHTS=10
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
